# Site settings
title: Daniel Kim
description: aspiring Data Scientist
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dkim92.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Daniel Kim
user_description: Aspiring data scientist with a background in information security and software development. Able to perform regression, classification, and clustering on data sets in addition to natural language processing, sentiment analysis, and develop a recommendation system (user-based, item-based, hybrid). 
user_title: Aspiring Data Scientist
email: dankim484@gmail.com
twitter_username: 
github_username:  dkim92
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
